services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist
    environment:
      ES_URL: http://archivist-es:9200
      REDIS_HOST: archivist-redis
      HOST_UID: ${USER_UID}
      HOST_GID: ${USER_UID}
      TA_HOST: tubearchivist.local
      TA_USERNAME: ${TUBEARCHIVIST_USER}
      TA_PASSWORD: ${TUBEARCHIVIST_PASSWORD}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      TZ: ${TZ}
    volumes:
      - /mnt/Youtube:/youtube
      - ${VOLUMES_DIR}/tubearchivist:/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.tubearchivist.entryPoints: https
      traefik.http.routers.tubearchivist.rule: Host(`yt.local.${DOMAIN}`)
      traefik.http.routers.tubearchivist.service: tubearchivist
      traefik.http.services.tubearchivist.loadbalancer.server.port: 8000
    restart: unless-stopped
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    expose:
      - "6379"
    volumes:
      - ${VOLUMES_DIR}/archivist-redis:/data
    depends_on:
      - archivist-es
    restart: unless-stopped
  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    environment:
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: true
      discovery.type: single-node
      path.repo: /usr/share/elasticsearch/data/snapshot
    volumes:
      - ${VOLUMES_DIR}/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - "9200"
    restart: unless-stopped

networks:
  proxy:
    external: true