services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    restart: always
    networks:
      proxy:
        ipv4_address: 172.18.1.2
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https

networks:
  proxy:
    external: true
