services:
  stats:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:tautulli
    volumes:
      - ${VOLUMES_DIR}/tautulli:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.tautulli.entryPoints: https
      traefik.http.routers.tautulli.rule: Host(`stats.local.${DOMAIN}`)

networks:
  proxy:
    external: true