services:
  auth:
    image: authelia/authelia
    container_name: auth
    volumes:
      - ${DOCKER_DIR}/authelia/configuration.yml:/config/configuration.yml
      - ${DOCKER_DIR}/authelia/users_database.yml:/config/users_database.yml
    environment:
      - TZ=${TZ}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_STORAGE_POSTGRES_USERNAME=${POSTGRES_USER}
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTHELIA_SESSION_REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.auth.entryPoints: https

networks:
  proxy:
    external: true