# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark
jwt_secret: ENV #any text or number you want to add here to create jwt Token

default_redirection_url: https://elotoja.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
  buffers:
    read: 4096
    write: 4096

log:
  level: debug

totp:
  issuer: elotoja.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  password_reset.disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: bypass
  rules:
    - domain:
        - "auth.elotoja.com"
      policy: bypass
    - domain: "*.elotoja.com"
      policy: two_factor
    - domain: "elotoja.com"
      policy: two_factor

session:
  name: authelia_session
  secret: ENV #any text or number you want to add here to create jwt Token
  expiration: 3600
  inactivity: 300
  domain: elotoja.com # Should match whatever your root protected domain is
  redis:
    host: 192.168.0.32
    port: 6379
    password: ENV
    database_index: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: ENV
  postgres:
    host: 192.168.0.32
    port: 5432
    database: authelia
    schema: public
    username: ENV
    password: ENV
    ssl:
      mode: disable

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
