services:
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      ACCEPT_EULA: Y
    volumes:
      - ${VOLUMES_DIR}/seq:/data
    ports:
      - 5341:5341
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.seq.entrypoints: https
      traefik.http.routers.seq.rule: Host(`seq.local.${DOMAIN}`)
      traefik.http.services.seq.loadbalancer.server.port: 80

networks:
  proxy:
    external: true
