services:
  pwd:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      SIGNUPS_ALLOWED: false
      INVITATIONS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
      DATABASE_URL: postgresql://${PG_VAULTWARDEN_USER}:${PG_VAULTWARDEN_PASSWORD}@postgres:5432/vaultwarden
    volumes:
      - ${VOLUMES_DIR}/vaultwarden:/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entryPoints: https

networks:
  proxy:
    external: true

