http:
  routers:
    grafana:
      rule: Host(`grafana.local.elotoja.com`) || Host(`grafana.server.elotoja.com`)
      entryPoints:
        - https
      middlewares:
        - auth@file
        - start-grafana@file
      service: grafana
    redis-commander:
      rule: Host(`redis.local.elotoja.com`) || Host(`redis.server.elotoja.com`)
      entryPoints:
        - https
      middlewares:
        - auth@file
        - start-redis-commander@file
      service: redis-commander
    portainer:
      rule: Host(`portainer.local.elotoja.com`) || Host(`portainer.server.elotoja.com`)
      entryPoints:
        - https
      middlewares:
        - auth@file
        - start-portainer@file
      service: portainer
    dockge:
      rule: Host(`docker.local.elotoja.com`) || Host(`docker.server.elotoja.com`)
      entryPoints:
        - https
      middlewares:
        - auth@file
        - start-dockge@file
      service: dockge

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    redis-commander:
      loadBalancer:
        servers:
          - url: "http://redis-commander:8081"
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    dockge:
      loadBalancer:
        servers:
          - url: "http://dockge:9000"

  ## MIDDLEWARES ##
  middlewares:
    # Only Allow Local networks
    local-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32 # localhost
          - 192.168.0.1/24 # LAN Subnet
          - 100.0.0.0/8 # Tailscale Subnet

    # Authelia guard
    auth:
      forwardauth:
        address: http://auth:9091/api/verify?rd=https://auth.local.elotoja.com/ # replace auth with your authelia container name
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    # Authelia basic auth guard
    auth-basic:
      forwardauth:
        address: http://auth:9091/api/verify?auth=basic # replace auth with your authelia container name
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

    gzip:
      compress: {}

    start-grafana:
      plugin:
        sablier:
          dynamic:
            displayName: "grafana"
            refreshFrequency: 5s
            showDetails: "true"
            theme: shuffle
          names: grafana
          sablierUrl: http://sablier:10000
          sessionDuration: 1h

    start-redis-commander:
      plugin:
        sablier:
          dynamic:
            displayName: "redis commander"
            refreshFrequency: 5s
            showDetails: "true"
            theme: shuffle
          names: redis-commander
          sablierUrl: http://sablier:10000
          sessionDuration: 1h

    start-portainer:
      plugin:
        sablier:
          dynamic:
            displayName: "portainer"
            refreshFrequency: 5s
            showDetails: "true"
            theme: shuffle
          names: portainer
          sablierUrl: http://sablier:10000
          sessionDuration: 1h

    start-dockge:
      plugin:
        sablier:
          dynamic:
            displayName: "dockge"
            refreshFrequency: 5s
            showDetails: "true"
            theme: shuffle
          names: dockge
          sablierUrl: http://sablier:10000
          sessionDuration: 1h

# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.6.0&config=intermediate&guideline=5.6
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
