services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: ${USER_UID}
    volumes:
      - ${VOLUMES_DIR}/grafana:/var/lib/grafana
    networks:
      - proxy

networks:
  proxy:
    external: true
