services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    restart: always
    networks:
      proxy:
        ipv4_address: 172.18.1.3
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entryPoints: https

networks:
  proxy:
    external: true
