services:
  requestrr:
    container_name: requestrr
    image: thomst08/requestrr
    volumes:
      - ${VOLUMES_DIR}/requestrr:/root/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.requestrr.entryPoints: https
      traefik.http.services.requestrr.loadbalancer.server.port: 4545

networks:
  proxy:
    external: true

