version: '3.8'

services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:latest
    container_name: zitadel
    command: start-from-init --masterkey "${ZITADEL_MASTERKEY}" --tlsMode disabled --config /config/config.yml
    environment:
      - ZITADEL_DATABASE_POSTGRES_HOST=postgres
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${POSTGRES_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - ZITADEL_EXTERNALSECURE=false
    volumes:
      - ${DOCKER_DIR}/zitadel/config.yml:/config/config.yml:ro
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.zitadel.entryPoints: https
      traefik.http.routers.zitadel.rule: Host(`zitadel.local.${DOMAIN}`)
      traefik.http.services.zitadel.loadbalancer.server.port: 8080
    restart: always

networks:
  proxy:
    external: true
