services:
  atuin:
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    command: server start
    volumes:
      - "${VOLUMES_DIR}/atuin:/config"
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@postgres/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
    networks:
      - proxy
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.atuin.entryPoints: https
      traefik.http.routers.atuin.service: atuin
      traefik.http.services.atuin.loadbalancer.server.port: 8888

networks:
  proxy:
    external: true
