services:
  sablier:
    container_name: sablier
    image: ghcr.io/acouvreur/sablier
    command:
      - start
      - --provider.name=docker
    volumes:
      - /run/user/${USER_UID}/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true

