services:
  quizer-api:
    image: ghcr.io/quizer-app/quizer:latest
    container_name: quizer-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 5000
      ASPNETCORE_URLS: http://+:5000
    volumes:
      - ${DOCKER_DIR}/quizer/appsettings.json:/app/appsettings.Production.json
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.quizer-api.entrypoints: https
      traefik.http.routers.quizer-api.rule: Host(`api.local.${DOMAIN}`)
      traefik.http.services.quizer-api.loadbalancer.server.port: 5000
  
  quizer-web:
    image: ghcr.io/quizer-app/quizer-web:latest
    container_name: quizer-web
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.quizer-web.entrypoints: https
      traefik.http.routers.quizer-web.rule: Host(`quizer.local.${DOMAIN}`)

networks:
  proxy:
    external: true
