Log:
  Level: info

ExternalSecure: true
ExternalDomain: zitadel.elotoja.com
ExternalPort: 443

Database:
  postgres:
    Host: postgres
    Port: 5432
    Database: zitadel
    User:
      SSL:
        Mode: "disable"
    Admin:
      SSL:
        Mode: "disable"
