version: "3"
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
      - TZ=${TZ}
    volumes:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    cap_add:
      - net_admin
      - sys_module