services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    group_add:
      - ${RENDER_GID}
    environment:
      TZ: ${TZ}
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      UMASK: 2
    volumes:
      - ${VOLUMES_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/:/media
      - /dev/shm:/transcode
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: https
      traefik.http.routers.jellyfin.rule: Host(`watch.local.${DOMAIN}`) || Host(`watch.${DOMAIN}`)
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096

networks:
  proxy:
    external: true
