version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      TZ: ${TZ}
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      UMASK: 002
    volumes:
      - ${VOLUMES_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/:/media
      - /dev/shm:/transcode
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: https
      traefik.http.routers.jellyfin.rule: Host(`watch.local.${DOMAIN}`, `watch.${DOMAIN}`)
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096

networks:
  proxy:
    external: true
