version: "3"
services:
  quizer-api:
    image: ghcr.io/quizer-app/quizer:latest
    container_name: quizer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${DOCKER_DIR}/quizer/appsettings.json:/app/appsettings.Production.json
      - ${VOLUMES_DIR}/quizer/logs:/app/logs
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.quizer-api.entrypoints: https
      traefik.http.routers.quizer-api.rule: Host(`api.local.${DOMAIN}`)
      traefik.http.services.quizer-api.loadbalancer.server.port: 5000
  
  quizer-web:
    image: ghcr.io/quizer-app/quizer-web:latest
    container_name: quizer-web
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.quizer-web.entrypoints: https
      traefik.http.routers.quizer-web.rule: Host(`quizer.local.${DOMAIN}`)

networks:
  proxy:
    external: true
