services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_DIR}/bazarr:/config
      - ${MEDIA_DIR}:/media
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.entryPoints: https

networks:
  proxy:
    external: true
