services:
  web:
    image: httpd:latest
    container_name: apache
    volumes:
      - ${DATA_DIR}/Website/:/usr/local/apache2/htdocs/
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.apache.entryPoints: https

networks:
  proxy:
    external: true
