services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - proxy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.entryPoints: https
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.local.${DOMAIN}`)

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: pgbackups
    user: postgres:postgres
    volumes:
      - /mnt/Backups/postgres:/backups
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres,elotoja,atuin,authelia,bazarr,radarr-main,semaphore,shlink,sonarr-main
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    restart: always

networks:
  proxy:
    external: true

volumes:
  pgadmin-data:
