services:
  redis:
    image: redis:7-alpine3.21
    container_name: redis
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${VOLUMES_DIR}/redis:/data
    ports:
      - 6379:6379
    restart: always
    networks:
      - proxy
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - proxy

networks:
  proxy:
    external: true

