services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks
    volumes:
      - /run/user/${USER_UID}/docker.sock:/var/run/docker.sock
      - dockge:/app/data
      - ${DOCKER_DIR}:/opt/stacks
    networks:
      - proxy
    # restart: unless-stopped
    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.dockge.entryPoints: https

volumes:
  dockge:

networks:
  proxy:
    external: true
