services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_DIR}/dockge:/app/data
      - ${DOCKER_DIR}:/opt/stacks
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.dockge.entryPoints: https
      traefik.http.routers.dockge.rule: Host(`docker.local.${DOMAIN}`)

networks:
  proxy:
    external: true