services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      TZ: "${TZ}"
      LOG_LEVEL: "info"
      DB_TYPE: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "${PG_JELLYSEERR_USER}"
      DB_PASS: "${PG_JELLYSEERR_PASSWORD}"
      DB_NAME: "jellyseerr"
      DB_LOG_QUERIES: "false"
      DB_USE_SSL: "false"
    volumes:
      - ${VOLUMES_DIR}/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.entryPoints: https
      traefik.http.routers.jellyseerr.rule: Host(`request.local.${DOMAIN}`) || Host(`request.server.${DOMAIN}`) || Host(`request.${DOMAIN}`)
      traefik.http.routers.jellyseerr.service: jellyseerr
      traefik.http.services.jellyseerr.loadbalancer.server.port: 5055

networks:
  proxy:
    external: true
